### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Rhenm091619** [ni5arga/Reddit-DailyDigest-Bot#1]
I got this error...

![untitled](https://github.com/ni5arga/Reddit-DailyDigest-Bot/assets/91313188/9b01c75a-2648-4643-be5a-c02e855e8360)

**Comment by ni5arga** [comment]
1. Can you copy paste the error logs here?
2. Which script specifically returned the errors?

Thanks for reporting.

**Comment by Rhenm091619** [comment]
The error logs is blank
